version: "3"
services:
  cash-scheduler-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: cash-scheduler-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "admin11@"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"

  cash-scheduler-client:
    image: ilyamatsuev/cash-scheduler-client
    container_name: cash-scheduler-client
    stdin_open: true
    ports:
      - "3000:3000"
      
  cash-scheduler-server:
    image: ilyamatsuev/cash-scheduler-server
    build:
      context: .
      dockerfile: ./CashSchedulerWebServer/Dockerfile
    container_name: cash-scheduler-server
    depends_on:
      - cash-scheduler-db
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      DbServer: "cash-scheduler-db"
      DbPort: "1433"
      DbUsername: "SA"
      DbPassword: "admin11@"
      DbName: "cash_scheduler"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8001"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/CashSchedulerWebServer.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
    volumes:
      - C:/Users/ASUS/.aspnet/https:/https/
